name: Build Lagrange.Milky Docker

on:
  push:
    branches: [ main ]
    paths:
      - Lagrange.Codec/**
      - Lagrange.Core/**
      - Lagrange.Proto/**
      - Lagrange.Proto.Generator/**
      - Lagrange.Milky/**
  pull_request:
    branches: [ main ]
    paths:
      - Lagrange.Codec/**
      - Lagrange.Core/**
      - Lagrange.Proto/**
      - Lagrange.Proto.Generator/**
      - Lagrange.Milky/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64

    steps:
        - uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Github Registry
          uses: docker/login-action@v3
          if: github.event_name != 'pull_request'
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: |
              ghcr.io/${{ github.repository_owner }}/lagrange.milky
            tags: |
              type=edge
              type=sha,event=branch
              type=ref,event=tag

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            file: Lagrange.Milky/Resources/Dockerfile
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            platforms: ${{ matrix.platform }}
